### PR TITLE
Add a pre-previous zone link for easier miniature crystal ball abuse.

### PR DESCRIPTION
**Pull request by Ilses**
By popular request. At some point I might consider throwing in a config option to select how many trailing zones you'd like to see.

### CODE REVIEW

**Comment by Ilses** [comment]
Oop, rebasing added an issue, I'll fix later today.

**Comment by Ilses** [comment]
Good enough.

Enable via e.g. "set chit.stats.display.previous_zones = <number of extra zones to show>". I can add a picker to the crystal ball if I feel like we change this setting with any real frequency.

**Comment by soolar** [comment]
This functionality already exists if you set trail as a full brick instead of the small form in stats. I guess it's not as configurable in that it'll show all the zones the mafia charpane would already show, rather than a set number, but it still accomplishes the same goal.

I'm open to the idea of changing the default layout to use trail as a brick instead of the snippet in stats that only shows the most recent zone, if the goal is to have the functionality be available to users by default, but then again even this change doesn't do that since it adds it via a configurable property.

This pull request does give me an idea though, and that's to add an area to the PR field for a screenshot with and without the PR's changes. Maybe if I saw it in action I'd understand the appeal of having it in stats instead of a brick and still showing multiple zones...

**Comment by tyrion-the-imp** [comment]
> This functionality already exists if you set trail as a full brick instead of the small form in stats. I guess it's not as configurable in that it'll show all the zones the mafia charpane would already show, rather than a set number, but it still accomplishes the same goal.

I believe the property 'recentLocations' allows one to confgure this.  Also, 'trail' can be added to the toolbar at the bottom (which is where I have it). Then a click will pop a list of the most recent locations instead of them being always visable,

**Pull request closed without merging**
